### PR TITLE
add chinese language

### PR DESCRIPTION
**Pull request by zx900930**

### CODE REVIEW

**Comment by Apen** [comment]
Hi,

First, thanks a lot for this update, im glad to see some contributions here.
In other way, i guess we need to implement the localisation with i18n, we dont want to copy/paste modification for each lang.

I do this in the last commit (today). Now we have:
- a lang/xxx.js with all the labels for a lang
- a js/xxx.characters.js prefix by the locale

With that, you only need to trigger this with your lang select and it will do the stuff for labels and external datas :
i18n.locale = 'xxx';

I implement an hide test with 'fr' as an example.

Could you provide a new PR for this with your menu and datas?

**Comment by zx900930** [comment]
> Hi,
> 
> First, thanks a lot for this update, im glad to see some contributions here.
> In other way, i guess we need to implement the localisation with i18n, we dont want to copy/paste modification for each lang.
> 
> I do this in the last commit (today). Now we have:
> 
> * a lang/xxx.js with all the labels for a lang
> * a js/xxx.characters.js prefix by the locale
> 
> With that, you only need to trigger this with your lang select and it will do the stuff for labels and external datas :
> i18n.locale = 'xxx';
> 
> I implement an hide test with 'fr' as an example.
> 
> Could you provide a new PR for this with your menu and datas?

At beginning I want to use the i18n,  but this is only the dist folder of your Vue project, so it takes more time than simply copy paste files....

**Comment by Apen** [comment]
It is not a full node vue project so its a little tricky to separate things. But,imo, this is easier to maintain than duplicate html and component. As u want 😁

**Comment by zx900930** [comment]
> It is not a full node vue project so its a little tricky to separate things. But,imo, this is easier to maintain than duplicate html and component. As u want 😁
Nope, I prefer the i18n method. I'll check it later and send new PR.

**Pull request closed without merging**
