### PR TITLE
add chinese language

### PR DESCRIPTION
**Pull request by zx900930**
changelog:

- add chinese language

- update french language files

- add a single line copy button(for export the data to a database or chat bot)

bugs:

- The "select-character" localization is not working.

- The report part localization is not working.

improvement:

- report: need a language based HP format,  we usually use 10k as a unit. 
`formatHp: function (num) {
            return Math.abs(num) > 999 ? Math.sign(num) * ((Math.abs(num) / 10000).toFixed(2)) + '万(10k in chinese)' : Math.sign(num) * Math.abs(num)
        },` 

- speed: we could have a push back % input, and add this value to enemies CR%.

### CODE REVIEW

**Comment by Apen** [comment]
Great work ! 

Ok for the first bug, i will fix it but what's the second one? Wich label missed from the report?

I will merge and fix then

**Comment by zx900930** [comment]
> Great work !
> 
> Ok for the first bug, i will fix it but what's the second one? Wich label missed from the report?
> 
> I will merge and fix then

the strings in report is hard coded in index.js.

like  Speed, Immunity set ,etc.

which made the report like this:
image

**Comment by Apen** [comment]
Ok, will look after it

**Comment by Apen** [comment]
Ok its fixed

**Pull request merged**
